- name: Set standard mailbox policies on {{ new_user_info.sam_account_name }}
  no_log: false
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Create credential"
      $password = ConvertTo-SecureString -String "{{ M365_PASSWORD }}" -AsPlainText -Force
      $credential = New-Object -TypeName System.Management.Automation.PSCredential("{{ M365_UPN }}", $password)

      Write-Verbose -Message "Connect to Exchange Online"
      Connect-ExchangeOnline -Credential $credential -ShowBanner:$false

      Write-Verbose -Message "Create the setting splat object"
      $standardMailboxSettings = @{
          AuditEnabled                      = $true
          AuditLogAgeLimit                  = 180
          AuditAdmin                        = @('Update', 'MoveToDeletedItems', 'SoftDelete', 'HardDelete', 'SendAs', 'SendOnBehalf', 'Create', 'UpdateFolderPermission')
          AuditDelegate                     = @('Update', 'SoftDelete', 'HardDelete', 'SendAs', 'Create', 'UpdateFolderPermissions', 'MoveToDeletedItems', 'SendOnBehalf')
          AuditOwner                        = @('UpdateFolderPermission', 'MailboxLogin', 'Create', 'SoftDelete', 'HardDelete', 'Update', 'MoveToDeletedItems')
          LitigationHoldEnabled             = $false
          MessageCopyForSentAsEnabled       = $true
          MessageCopyForSendOnBehalfEnabled = $true
          RetentionPolicy                   = 'Default MRM Policy'    
          Identity                          = '{{ new_user_info.sam_account_name }}'
      }

      Write-Verbose -Message "Set the policies on the mailbox"
      Set-EXOMailbox @standardMailboxSettings
