- name: Get EXO Mailbox Information
  no_log: true
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Create credential"
      $password = ConvertTo-SecureString -String "{{ M365_PASSWORD }}" -AsPlainText -Force
      $credential = New-Object -TypeName System.Management.Automation.PSCredential("{{ M365_UPN }}", $password)

      Write-Verbose -Message "Set Tls 1.2 for the session"
      [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
      
      Write-Verbose -Message "Connect to Exchange Online"
      Connect-ExchangeOnline -Credential $credential -ShowBanner:$false

      Get-EXOMailbox -Anr {{ identity }} -PropertySets {{ property_sets }}
  register: online_mailbox

- set_fact:
    exo_mailbox: "{{ online_mailbox.output }}"