- name: Create remote mailbox for {{ new_user_info.SamAccountName }}
  no_log: false
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Establish connection to Exchange on-premises"
      $password = ConvertTo-SecureString -String "{{ AD_PASSWORD }}" -AsPlainText -Force
      $credential = New-Object -TypeName System.Management.Automation.PSCredential("{{ AD_USERNAME }}", $password)
      $hx = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "{{ exchange_uri }}" -Name HybridServer -Credential $credential
      Import-PSSession -Session $hx | Out-Null

      $san = "{{ new_user_info.SamAccountName }}"
      $upn = "{{ new_user_info.UserPrincipalName }}"
      $rra = "$san@{{ m365_routing_domain }}"

      Enable-RemoteMailbox -Identity $san -PrimarySmtpAddress $upn -RemoteRoutingAddress $rra | Out-Null
      Enable-RemoteMailbox -Identity $san -Archive | Out-Null
      Set-RemoteMailbox -Identity $san -EmailAddressPolicyEnabled $true | Out-Null
      Get-ADUser -Identity $san -Properties adminDescription | Select-Object -Property adminDescription
      Set-ADUser -Identity $san -Add @{"{{ extension_attribute_string }}"} -Clear adminDescription | Out-Null
  register: user_password

- set_fact:
    password: "{{ user_password.output }}"

- name: Create HTML report
  ansible.builtin.template:
      src: new-user-email.j2
      dest: "/tmp/{{ tower_job_id }}.html"
  delegate_to: 127.0.0.1

- name: Send report
  community.general.sendgrid:
    api_key: "{{ SENDGRID_API_KEY }}"
    to_addresses: "{{ recipient_email | split('\n') }}"
    from_address: "{{ from_address }}"
    from_name: "{{ from_name }}"
    subject: "Job {{ tower_job_id }}: New Employee Account"
    body: "{{ lookup('file', '/tmp/{{ tower_job_id }}.html') }}"
    html_body: true
  delegate_to: 127.0.0.1