- name: Create remote mailbox for {{ new_user_info.sam_account_name }}
  no_log: false
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Establish connection to Exchange on-premises"
      $password = ConvertTo-SecureString -String "{{ AD_PASSWORD }}" -AsPlainText -Force
      $credential = New-Object -TypeName System.Management.Automation.PSCredential("{{ AD_USERNAME }}", $password)
      $hx = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "{{ exchange_uri }}" -Name HybridServer -Credential $credential
      Import-PSSession -Session $hx | Out-Null

      $san = "{{ new_user_info.sam_account_name }}"
      $upn = "{{ new_user_info.user_principal_name }}"
      $rra = "$san@{{ m365_routing_domain }}"

      Enable-RemoteMailbox -Identity $san -PrimarySmtpAddress $upn -RemoteRoutingAddress $rra
      Enable-RemoteMailbox -Identity $san -Archive
      Set-RemoteMailbox -Identity $san -EmailAddressPolicyEnabled $true
      Set-ADUser -Identity $san -Add @{extensionAttribute6='baseUserLicense'}
