- name: Read distribution group info
  no_log: true
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Establish connection to Exchange on-premises"
      $password = ConvertTo-SecureString -String "{{ AD_PASSWORD }}" -AsPlainText -Force
      $credential = New-Object -TypeName System.Management.Automation.PSCredential("{{ AD_USERNAME }}", $password)
      $hx = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "{{ exchange_uri }}" -Name HybridServer -Credential $credential
      Import-PSSession -Session $hx -WarningAction SilentlyContinue | Out-Null

      Write-Verbose -Message "Return new group"
      if (Get-DistributionGroup -Identity "{{ distribution_group_identity }}") {
        Write-Output (Get-DistributionGroup -Identity "{{ distribution_group_identity }}" | Select-Object -Property DisplayName,Alias,PrimarySmtpAddress,GroupType)
      }
  register: distribution_group_detail

- set_stats:
    data:
      distribution_group: "{{ distribution_group_detail.output }}"
