- name: Create AD User
  no_log: false
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Create user variables"
      $fn = '{{ first_name }}'
      $init = '{{ initials }}'
      $ln = '{{ last_name }}'
      $eid = '{{ employee_id }}'
      $displayName = '{{ display_name }}'

      if ($init) {
        $sam_account_name = "$($fn.ToLower()[0])$($init.ToLower()[0])$($ln.ToLower())"
      } else {
        $sam_account_name = "$($fn.ToLower()[0])$($ln.ToLower())"
      }

      $departmentUserOU = switch('{{ department }}') {
        'Chief Executive' { "OU=CEO,{{ user_ou_path }}" }
        'District Attorney' { "OU=DA,{{ user_ou_path }}" }
        'DoIT' { "OU=DoIT,{{ user_ou_path }}" }
        'Finance' { "OU=FIN,{{ user_ou_path }}" }
        'Police' { "OU=PD,{{ user_ou_path }}" }
        'Sheriff' { "OU=SO,{{ user_ou_path }}" }
      }

      $user_principal_name = "$sam_account_name@{{ email_domain }}"
      $password = "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits,punctuation length=14') }}"

      try {
        Write-Verbose -Message "Create user splat"
        $userData = @{
          GivenName = $fn
          Initials = $init
          Surname = $ln
          Title = '{{ job_title }}'
          Department = '{{ department }}'
          Path = $departmentUserOU
          SamAccountName = $sam_account_name
          DisplayName = $displayName
          Name = "$fn $ln"
          EmployeeID = $eid
          EmployeeNumber = $eid
          UserPrincipalName = $user_principal_name
          AccountPassword = (ConvertTo-SecureString -AsPlainText -Force -String $password)
          Enabled = $true
        }
 
        Write-Verbose -Message "Create user object"
        New-ADUser @userData | Out-Null
        Write-Verbose -Message "Add password to account temporarily"
        Set-ADUser -Identity $sam_account_name -Add @{adminDescription=$password}

        Write-Verbose "Return the new user data"
        Write-Output -InputObject $userData
      } catch {
        Write-Output $Error[0]
        $Ansible.Failed = $true
      }
  register: ad_user_data

- set_fact:
    new_user_info: "{{ ad_user_data.output }}"