- name: Set standard mailbox policies on {{ identity }}
  no_log: true
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Create credential"
      $password = ConvertTo-SecureString -String "{{ M365_PASSWORD }}" -AsPlainText -Force
      $credential = New-Object -TypeName System.Management.Automation.PSCredential("{{ M365_UPN }}", $password)

      Write-Verbose -Message "Set Tls 1.2 for the session"
      [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
      
      Write-Verbose -Message "Connect to Exchange Online"
      Connect-ExchangeOnline -Credential $credential -ShowBanner:$false

      Write-Verbose -Message "Create the setting splat object"
      $standardMailboxSettings = @{
          AuditEnabled                      = $true
          AuditLogAgeLimit                  = 180
          AuditAdmin                        = @('Update', 'MoveToDeletedItems', 'SoftDelete', 'HardDelete', 'SendAs', 'SendOnBehalf', 'Create', 'UpdateFolderPermissions')
          AuditDelegate                     = @('Update', 'SoftDelete', 'HardDelete', 'SendAs', 'Create', 'UpdateFolderPermissions', 'MoveToDeletedItems', 'SendOnBehalf')
          AuditOwner                        = @('UpdateFolderPermissions', 'MailboxLogin', 'Create', 'SoftDelete', 'HardDelete', 'Update', 'MoveToDeletedItems')
          LitigationHoldEnabled             = $false
          MessageCopyForSentAsEnabled       = $true
          MessageCopyForSendOnBehalfEnabled = $true
        #  RetentionPolicy                   = 'Default MRM Policy'
          RetainDeletedItemsFor             = '30.00:00:00'    
          Identity                          = '{{ identity }}'
      }

      Write-Verbose -Message "Set the policies on the mailbox"
      Set-Mailbox @standardMailboxSettings
