- name: Reset a user password
  no_log: true
  ansible.windows.win_powershell:
    script: |
      $password = "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits,punctuation length=14') }}"
      $secPassword = ConvertTo-SecureString -AsPlainText -Force -String $password
      Set-ADAccountPassword -Identity {{ sam_account_name }} -NewPassword $secPassword -Reset
      Write-Output -InputObject $password
  register: new_password

- set_fact:
    password: "{{ new_password.output }}"