- name: Update AD User
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Update the user"
      $string = "{{ attribute }}='{{ value }}'"
      Set-ADUser -Identity {{ sam_account_name }} -Add @{ $string }
  register: script_output

- name: Display result
  debug:
    msg: "{{ script_output.output }}"