- name: Update AD User
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Update the user"
      $string = "{{ attribute }}='{{ value }}'"
      Write-Output "Set-ADUser -Add @{ $string }"
  register: script_output

- name: Display result
  debug:
    msg: "{{ script_output.output }}"