- name: Update AD User
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Create user update splat"
      $data = "{{ parameters }}" | ConvertFrom-Json
      Write-Output "$($data[0].Name) = $($data[0].Value)"
  register: script_output

- name: Display result
  debug:
    msg: "{{ script_output.output }}"