- name: Create distribution group
  no_log: true
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Establish connection to Exchange on-premises"
      $password = ConvertTo-SecureString -String "{{ AD_PASSWORD }}" -AsPlainText -Force
      $credential = New-Object -TypeName System.Management.Automation.PSCredential("{{ AD_USERNAME }}", $password)
      $hx = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "{{ exchange_uri }}" -Name HybridServer -Credential $credential
      Import-PSSession -Session $hx | Out-Null

      $groupData = @{
        SamAccountName = "{{ sam_account_name }}"
        Alias = "{{ sam_account_name }}"
        Name = "{{ display_name }}"
        DisplayName = "{{ display_name }}"
        PrimarySmtpAddress = "{{ email_address }}"
        OrganizationalUnit = "{{ group_ou_path }}"
      }

      Write-Verbose -Message "Create the distribution group"
      New-DistributionGroup @groupData | Out-Null

      Write-Verbose -Message "Return new group"
      if (Get-DistributionGroup -Identity $groupData.SamAccountName) {
        Write-Output (Get-DistributionGroup -Identity $groupData.SamAccountName | Select-Object -Property DisplayName,Alias,PrimarySmtpAddress,Type)
      }
  register: distribution_group_detail

- set_stats:
  data:
    distribution_group: "{{ distribution_group_detail.output }}"
