- name: Add distribution group member
  no_log: true
  ansible.windows.win_powershell:
    script: |
      Write-Verbose -Message "Establish connection to Exchange on-premises"
      $password = ConvertTo-SecureString -String "{{ AD_PASSWORD }}" -AsPlainText -Force
      $credential = New-Object -TypeName System.Management.Automation.PSCredential("{{ AD_USERNAME }}", $password)
      $hx = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri "{{ exchange_uri }}" -Name HybridServer -Credential $credential
      Import-PSSession -Session $hx -WarningAction SilentlyContinue | Out-Null

      Write-Verbose -Message "Update distribution group membership"
      $members = if ("{{ add_member }}" -match "`n") { -split "{{ add_member }}" } else { "{{ add_member }}" }
      $members | ForEach-Object { Remove-DistributionGroupMember -Identity '{{ distribution_group_identity }}' -Member $_ }

